
import type { Trip, UserProfile } from './types';

export const mockTrips: Trip[] = [
  {
    id: '1',
    shipmentId: '#845-GDL-MTY',
    origin: 'Guadalajara, JAL',
    destination: 'Monterrey, N.L.',
    status: 'En Progreso',
    price: 25000,
    cargoDetails: '2 Toneladas de Electrónicos',
    addresses: {
      pickup: 'Av. Vallarta 123, Guadalajara, 44100',
      delivery: 'Av. Constitución 456, Monterrey, 64000',
    },
    bidInfo: 'Ganada por $25,000 MXN',
    estimatedTimes: [
      { label: 'Llegada a Origen', time: '10:00 AM', status: 'completed' },
      { label: 'Inicio de Carga', time: '11:00 AM', status: 'completed' },
      { label: 'Fin de Carga', time: '1:00 PM', status: 'completed' },
      { label: 'Llegada a Destino', time: '8:00 AM (Mañana)', status: 'pending' },
    ],
    notes: [
        { author: 'Moderador', message: 'Favor de confirmar llegada a destino.', timestamp: 'hace 1h' }
    ],
    documents: [
        { name: 'Bill_of_Lading.pdf', url: '#', uploadedAt: '2024-07-29' }
    ],
    miles: 520,
    weight: 4000,
    trailerType: 'Caja Seca 53ft',
  },
  {
    id: '2',
    shipmentId: '#788-PUE-MER',
    origin: 'Puebla, PUE',
    destination: 'Mérida, YUC',
    status: 'En Progreso',
    price: 32000,
    cargoDetails: 'Material de construcción',
    addresses: {
      pickup: 'Blvd. Hermanos Serdán 789, Puebla, 72140',
      delivery: 'Calle 60 101, Mérida, 97000',
    },
    bidInfo: 'Ganada por $32,000 MXN',
    estimatedTimes: [
        { label: 'Llegada a Origen', time: 'Ayer 4:00 PM', status: 'completed' },
        { label: 'Llegada a Destino', time: 'Mañana 9:00 PM', status: 'pending' },
    ],
    notes: [],
    documents: [],
    miles: 750,
    weight: 20000,
    trailerType: 'Plataforma',
  },
  {
    id: '3',
    shipmentId: '#654-TIJ-MEX',
    origin: 'Tijuana, B.C.',
    destination: 'CDMX',
    status: 'Completado',
    price: 45000,
    cargoDetails: 'Productos refrigerados',
    addresses: {
      pickup: 'Zona Otay, Tijuana, 22425',
      delivery: 'Central de Abastos, CDMX, 09040',
    },
    bidInfo: 'Ganada por $45,000 MXN',
    estimatedTimes: [],
    notes: [],
    documents: [],
    miles: 1700,
    weight: 15000,
    trailerType: 'Refrigerado 53ft',
  },
  {
    id: '4',
    shipmentId: '#998-CUN-CDMX',
    origin: 'Cancún, Q.R.',
    destination: 'CDMX',
    status: 'En Progreso',
    price: 55000,
    cargoDetails: 'Equipo hotelero, 5 toneladas',
    addresses: {
      pickup: 'Zona Hotelera, Cancún, 77500',
      delivery: 'Polanco, CDMX, 11550',
    },
    bidInfo: 'Ganada por $55,000 MXN',
    estimatedTimes: [
      { label: 'Llegada a Origen', time: 'Hoy 8:00 AM', status: 'completed' },
      { label: 'Inicio de Carga', time: 'Hoy 9:00 AM', status: 'completed' },
      { label: 'Fin de Carga', time: 'Hoy 12:00 PM', status: 'pending' },
      { label: 'Llegada a Destino', time: 'Pasado mañana 4:00 PM', status: 'pending' },
    ],
    notes: [],
    documents: [],
    miles: 1000,
    weight: 10000,
    trailerType: 'Caja Seca 53ft',
  },
   {
    id: '5',
    shipmentId: '#332-VER-GDL',
    origin: 'Veracruz, VER',
    destination: 'Guadalajara, JAL',
    status: 'Completado',
    price: 38000,
    cargoDetails: 'Café de exportación, 10 toneladas',
    addresses: {
      pickup: 'Puerto de Veracruz, Veracruz, 91700',
      delivery: 'Zona Industrial, Guadalajara, 44940',
    },
    bidInfo: 'Ganada por $38,000 MXN',
    estimatedTimes: [],
    notes: [ { author: 'Juan Pérez', message: 'Entrega finalizada sin inconvenientes.', timestamp: 'hace 2 días' } ],
    documents: [ { name: 'POD_332.pdf', url: '#', uploadedAt: '2024-07-27' } ],
    miles: 600,
    weight: 20000,
    trailerType: 'Caja Seca 53ft',
  },
  {
    id: '6',
    shipmentId: '#412-MTY-BJX',
    origin: 'Monterrey, N.L.',
    destination: 'León, GTO',
    status: 'Completado',
    price: 18000,
    cargoDetails: 'Autopartes',
    addresses: {
      pickup: 'Parque Industrial Stiva, Monterrey, 66600',
      delivery: 'Parque Industrial Pilba, León, 37440',
    },
    bidInfo: 'Ganada por $18,000 MXN',
    estimatedTimes: [],
    notes: [],
    documents: [{ name: 'POD_412.pdf', url: '#', uploadedAt: '2024-07-26' }],
    miles: 300,
    weight: 8000,
    trailerType: 'Caja Seca 48ft',
  },
];

export const mockProfile: UserProfile = {
  name: 'Juan Pérez',
  email: 'juan.perez@transportes.com',
  vehicle: 'Kenworth T680 (Placas: A12-34-BC)',
  avatarUrl: '/images/profile-avatar.jpg',
  rating: 4.8,
};
