
import { ArrowLeft } from 'lucide-react';
import { Button } from '@/components/ui/button';
import Link from 'next/link';

const Section = ({ title, children }: { title: string, children: React.ReactNode }) => (
  <section className="space-y-4">
    <h2 className="text-2xl font-semibold border-b pb-2">{title}</h2>
    <div className="space-y-3 text-muted-foreground">{children}</div>
  </section>
);

export default function TermsOfServicePage() {
  return (
    <div className="bg-background text-foreground">
      <div className="container mx-auto p-4 md:p-8 max-w-4xl">
        <div className="mb-8">
          <Button variant="ghost" asChild>
            <Link href="/">
              <ArrowLeft className="mr-2 h-4 w-4" />
              Volver al Inicio
            </Link>
          </Button>
        </div>
        
        <header className="mb-10">
          <h1 className="text-4xl font-bold text-primary mb-3">Condiciones de uso de UCarga</h1>
          <p className="text-lg text-muted-foreground">Última modificación: 25 de Octubre de 2025</p>
        </header>

        <div className="space-y-10">
          <Section title="Sección 1: Relaciones contractuales">
            <p>Estas Condiciones de Uso («Condiciones») rigen el acceso o uso por usted, un individuo o entidad, de las aplicaciones (incluyendo aplicaciones móviles), sitios web, contenidos, productos y servicios (colectivamente, los «Servicios») puestos a disposición por UCarga y sus subsidiarias y afiliadas (colectivamente, «UCarga»).</p>
            <p><strong>LEA ATENTAMENTE ESTAS CONDICIONES ANTES DE ACCEDER Y UTILIZAR LOS SERVICIOS.</strong></p>
            <p>En estas Condiciones, las palabras «incluido» e «incluye» significan «incluido, pero no limitado a». Su acceso y uso de los Servicios constituye su aceptación de estas Condiciones, que establecen una relación contractual entre usted y UCarga. Estos Términos sustituyen a cualquier otro acuerdo con respecto al objeto de estos Términos, excepto con respecto a cualquier acuerdo de remitente o transportista entre el remitente o transportista que usted representa (según corresponda) y UCarga, dicho acuerdo no será sustituido por estos Términos, y en la medida en que dicho otro acuerdo sea incompatible con estos Términos, dicho otro acuerdo regirá.</p>
            <p>UCarga podrá, en cualquier momento y por cualquier motivo, sin previo aviso, dejar de ofrecerle acceso a los Servicios o a cualquier parte de los mismos o denegarle el acceso a los Servicios o a cualquier parte de los mismos.</p>
            <p>Usted se compromete a mantener en secreto todas sus credenciales de inicio de sesión para acceder o utilizar los Servicios y a permitir únicamente a sus usuarios autorizados que accedan o utilicen los Servicios. Usted es responsable de toda la actividad que se produzca bajo sus credenciales de acceso.</p>
            <p>UCarga puede modificar estas Condiciones de vez en cuando. Las modificaciones entrarán en vigor en el momento en que UCarga publique dichas Condiciones actualizadas en esta ubicación. Su acceso o uso continuado de los Servicios después de dicha publicación constituye su consentimiento a quedar vinculado por las Condiciones, en su versión modificada. Consulte el Aviso de privacidad de UCarga para obtener información sobre nuestra recopilación y uso de información personal en relación con los Servicios.</p>
          </Section>

          <Section title="Sección 2: Licencia">
            <p>Sujeto al cumplimiento de estas Condiciones, UCarga le otorga una licencia limitada, no exclusiva, no sublicenciable, revocable e intransferible para acceder y utilizar los Servicios. Todos los derechos no concedidos expresamente en este documento están reservados por UCarga (y sus afiliados, según corresponda) y los licenciantes de UCarga.</p>
            <h3 className="text-xl font-semibold pt-4">Restricciones</h3>
            <p>Usted no puede, y no puede autorizar a otros a: (i) eliminar cualquier derecho de autor, marca comercial u otros avisos de propiedad de cualquier parte de los Servicios; (ii) reproducir, modificar, preparar trabajos derivados basados en, distribuir, licenciar, arrendar, vender, revender, transferir, mostrar públicamente, ejecutar públicamente, transmitir, transmitir, difundir o explotar de cualquier otra forma los Servicios, excepto en los casos expresamente permitidos por UCarga; (iii) descompilar, desensamblar, aplicar ingeniería inversa o intentar obtener de cualquier otro modo el código fuente o la tecnología, metodologías o algoritmos subyacentes de los Servicios, salvo en la medida en que lo permita la legislación aplicable; (iv) enlazar, reflejar o enmarcar cualquier parte de los Servicios; (v) provocar o iniciar cualquier programa o secuencia de comandos con el fin de raspar, indexar, inspeccionar o, de otro modo, extraer datos de cualquier parte de los Servicios, o sobrecargar o dificultar indebidamente el funcionamiento y/o la funcionalidad de cualquier aspecto de los Servicios; o (vi) intentar obtener acceso no autorizado o perjudicar cualquier aspecto de los Servicios o sus sistemas o redes relacionados.</p>
            <h3 className="text-xl font-semibold pt-4">Propiedad</h3>
            <p>Los Servicios y todos sus derechos son y seguirán siendo propiedad de UCarga o de los licenciantes de UCarga. Ni estas Condiciones ni su uso de los Servicios le transmiten ni le otorgan ningún derecho: (i) en los Servicios o relacionados con ellos, salvo la licencia limitada concedida anteriormente; o (ii) utilizar o hacer referencia en modo alguno a los nombres de empresas, logotipos, nombres de productos y servicios, marcas comerciales o marcas de servicios de UCarga o de los licenciantes de UCarga.</p>
          </Section>

          <Section title="Sección 3: Renuncias; Limitación de responsabilidad; Indemnización">
            <h3 className="text-xl font-semibold">DESCARGO DE RESPONSABILIDAD</h3>
            <p>LOS SERVICIOS SE PRESTAN «TAL CUAL» Y «SEGÚN DISPONIBILIDAD». UCarga RENUNCIA A TODAS LAS REPRESENTACIONES Y GARANTÍAS, EXPRESAS, IMPLÍCITAS O ESTATUTARIAS, NO ESTABLECIDAS EXPRESAMENTE EN ESTOS TÉRMINOS, INCLUIDAS LAS GARANTÍAS IMPLÍCITAS DE COMERCIABILIDAD, IDONEIDAD PARA UN FIN DETERMINADO Y NO INFRACCIÓN. ADEMÁS, UCarga NO REPRESENTA, GARANTIZA NI ASEGURA LA FIABILIDAD, PUNTUALIDAD, CALIDAD, IDONEIDAD O DISPONIBILIDAD DE LOS SERVICIOS, NI QUE LOS SERVICIOS SEAN ININTERRUMPIDOS O ESTÉN LIBRES DE ERRORES. USTED ACEPTA QUE TODO EL RIESGO DERIVADO DE SU ACCESO O USO DE LOS SERVICIOS RECAE EXCLUSIVAMENTE EN USTED, EN LA MEDIDA MÁXIMA PERMITIDA POR LA LEGISLACIÓN APLICABLE.</p>
            <h3 className="text-xl font-semibold pt-4">LIMITACIÓN DE RESPONSABILIDAD</h3>
            <p>UCarga NO SERÁ RESPONSABLE POR DAÑOS INDIRECTOS, INCIDENTALES, ESPECIALES, EJEMPLARES, PUNITIVOS O CONSECUENTES, INCLUYENDO PERO NO LIMITADO A LA PÉRDIDA DE BENEFICIOS, PÉRDIDA DE DATOS, LESIONES PERSONALES O DAÑOS A LA PROPIEDAD RELACIONADOS CON, EN CONEXIÓN CON, O DE OTRA MANERA RESULTANTES DE CUALQUIER USO DE LOS SERVICIOS, INCLUSO SI UCarga HA SIDO ADVERTIDO DE LA POSIBILIDAD DE TALES DAÑOS. UCarga NO SERÁ RESPONSABLE DE NINGÚN DAÑO, RESPONSABILIDAD O PÉRDIDA DERIVADOS DE: (i) SU USO O CONFIANZA EN LOS SERVICIOS O SU INCAPACIDAD PARA ACCEDER O UTILIZAR LOS SERVICIOS; O (ii) CUALQUIER TRANSACCIÓN O RELACIÓN ENTRE USTED Y CUALQUIER PROVEEDOR TERCERO, INCLUSO SI UCarga HA SIDO ADVERTIDO DE LA POSIBILIDAD DE TALES DAÑOS. UCarga NO SERÁ RESPONSABLE DE LOS RETRASOS O INCUMPLIMIENTOS DERIVADOS DE CAUSAS AJENAS AL CONTROL RAZONABLE DE UCarga. EN NINGÚN CASO LA RESPONSABILIDAD TOTAL DE UCarga ANTE USTED EN RELACIÓN CON LOS SERVICIOS POR TODOS LOS DAÑOS, PÉRDIDAS Y CAUSAS DE ACCIÓN EXCEDERÁ LOS QUINIENTOS DÓLARES ESTADOUNIDENSES (US $500).</p>
            <p>UCarga NO CONTROLA, RESPALDA NI ASUME RESPONSABILIDAD ALGUNA POR EL CONTENIDO DE LOS USUARIOS O DE TERCEROS DISPONIBLE EN LOS SERVICIOS O VINCULADO A ELLOS (INCLUIDA LA INFORMACIÓN SOBRE LOS SERVICIOS PROPORCIONADA POR LOS USUARIOS O POR LOS EXPEDIDORES). UCarga NO PUEDE Y NO DECLARA NI GARANTIZA QUE LOS SERVICIOS O SERVIDORES ESTÉN LIBRES DE VIRUS U OTROS COMPONENTES DAÑINOS.</p>
            <h3 className="text-xl font-semibold pt-4">Indemnización</h3>
            <p>Usted se compromete a indemnizar y eximir a UCarga y sus afiliados y sus respectivos funcionarios, directores, empleados y agentes de cualquier y toda reclamación, demanda, pérdida, responsabilidad y gastos (incluyendo honorarios de abogados), que surjan de o en conexión con: (i) su uso de los Servicios; y/o (ii) su incumplimiento o violación de cualquiera de estas Condiciones.</p>
          </Section>

          <Section title="Sección 4: Resolución de litigios">
            <h3 className="text-xl font-semibold">Arbitraje</h3>
            <p>Usted acepta que cualquier disputa, reclamación o controversia que surja de o en relación con estos Términos, incluyendo el incumplimiento, terminación, ejecución, interpretación o validez de los mismos o el uso de los Servicios (colectivamente, «Disputas») debe ser resuelto única y definitivamente por arbitraje confidencial y final entre usted y UCarga, excepto que cada parte conserva el derecho de iniciar una acción individual en un tribunal de reclamos menores y el derecho de solicitar medidas cautelares u otra compensación equitativa en un tribunal de jurisdicción competente para evitar la infracción real o amenaza de infracción, apropiación indebida o violación de los derechos de autor, marcas comerciales, secretos comerciales, patentes u otros derechos de propiedad intelectual de una parte. Usted reconoce y acepta que tanto usted como UCarga renuncian al derecho a un juicio con jurado o a participar como demandante o colectivo en cualquier pretendida demanda colectiva o procedimiento representativo. Además, a menos que usted y UCarga acuerden lo contrario por escrito, el árbitro no podrá consolidar las reclamaciones de más de una persona, y no podrá presidir ninguna forma de procedimiento colectivo o representativo. Si este párrafo específico se considera inaplicable, entonces la totalidad de esta sección «Resolución de litigios» se considerará nula. Salvo lo dispuesto en la frase anterior, esta sección de «Resolución de disputas» sobrevivirá a cualquier rescisión de estas Condiciones.</p>
            <h3 className="text-xl font-semibold pt-4">Reglamento de arbitraje y ley aplicable</h3>
            <p>El arbitraje será administrado por Judicial Arbitration and Mediation Services («JAMS») en Mérida, Yucatán, México, o en otro lugar determinado por UCarga. Cualquier arbitraje realizado de conformidad con estas Condiciones se regirá por la Ley Federal de Arbitraje (9 U.S.C. § 1-16).</p>
            <h3 className="text-xl font-semibold pt-4">Negociación</h3>
            <p>Antes de iniciar un arbitraje, usted y UCarga acuerdan notificar a la otra parte por escrito de cualquier disputa y tratar de negociar una resolución informal. Las notificaciones a UCarga deben enviarse a UCarga, a: calle 62e, 332, Magnolias, Mérida, Yucatán, México. Ninguna de las partes iniciará el arbitraje hasta 30 días después del envío de la notificación.</p>
            <h3 className="text-xl font-semibold pt-4">Decisión del árbitro</h3>
            <p>Un laudo dictado en relación con el arbitraje de conformidad con esta Sección 4 será definitivo y vinculante para usted y UCarga, y la sentencia sobre dicho laudo podrá ser presentada y ejecutada en cualquier tribunal de jurisdicción competente. La indemnización por daños y perjuicios concedida por el árbitro debe ser coherente con los términos de la sección «Limitación de responsabilidad» anterior en cuanto a los tipos y los importes de los daños y perjuicios por los que una parte puede ser considerada responsable. El árbitro podrá conceder medidas declaratorias o cautelares únicamente a favor del demandante y sólo en la medida necesaria para proporcionar la reparación que justifique la demanda individual del demandante.</p>
          </Section>
          
          <Section title="Sección 5: Transporte y otros servicios">
            <p>UCarga NO ES UN TRANSPORTISTA. NINGUNA INTERPRETACIÓN DE LAS OBSERVACIONES ESCRITAS U ORALES DE CUALQUIER ACUERDO O DOCUMENTO SE INTERPRETARÁ EN EL SENTIDO DE QUE UCarga ES UN TRANSPORTISTA. Un «transportista», tal y como se utiliza en estas Condiciones, significa cualquier transportista o empresa de transporte por carretera, incluido un transportista tal y como se define en 49 USC §13102(14) con autoridad emitida por el gobierno federal y/o estatal aplicable o un transportista con autoridad emitida por cualquier otra autoridad gubernamental aplicable. Ciertas entidades de UCarga son agentes de carga con licencia federal, tal como se define en 49 USC §13102(2), en virtud de la autoridad otorgada por la Administración Federal de Seguridad de Autotransportes del Departamento de Transporte de los Estados Unidos.</p>
            <h3 className="text-xl font-semibold pt-4">Mensajes de texto y llamadas telefónicas</h3>
            <p>Usted acepta que UCarga puede ponerse en contacto con usted por teléfono o mensajes SMS (incluyendo por un sistema de marcación telefónica automática y / o con una voz artificial o pregrabada) en cualquiera de los números de teléfono proporcionados por usted o en su nombre, incluso con fines de marketing. Usted entiende que no está obligado a dar este consentimiento como condición para adquirir ninguna propiedad, bien o servicio. Usted también entiende que puede optar por no recibir mensajes SMS de UCarga en cualquier momento, ya sea respondiendo con la palabra «STOP» utilizando el dispositivo móvil que está recibiendo los mensajes.</p>
            <h3 className="text-xl font-semibold pt-4">Contenido proporcionado por el usuario</h3>
            <p>UCarga puede, a discreción de UCarga, permitirle de vez en cuando para enviar, cargar, publicar o poner a disposición de UCarga a través de los Servicios de texto, audio, visual u otro contenido e información, incluyendo información de carga, comentarios y opiniones relacionadas con los Servicios, calificaciones y comentarios (incluyendo de los transportistas e instalaciones), el inicio de las solicitudes de apoyo, y la presentación de entradas para concursos y promociones («Contenido de Usuario»). Cualquier Contenido de Usuario proporcionado por usted seguirá siendo de su propiedad. Sin embargo, al proporcionar Contenido del usuario a UCarga, usted otorga a UCarga una licencia mundial, perpetua, irrevocable, transferible, libre de regalías, con derecho a sublicenciar, para usar, copiar, modificar, crear trabajos derivados, distribuir, mostrar públicamente, ejecutar públicamente, y explotar de cualquier otra manera dicho Contenido de Usuario en todos los formatos y canales de distribución conocidos actualmente o que se conciban en el futuro (incluyendo en relación con los Servicios y el negocio de UCarga y en sitios y servicios de terceros), sin previo aviso o consentimiento de usted, y sin el requisito de pago a usted o cualquier otra persona o entidad.</p>
            <p>Usted declara y garantiza que: (i) usted es el único y exclusivo propietario de todo el Contenido del Usuario o tiene todos los derechos, licencias, consentimientos y liberaciones necesarios para conceder a UCarga la licencia del Contenido del Usuario según lo establecido anteriormente; y (ii) ni el Contenido del usuario, ni su envío, carga, publicación o puesta a disposición de otro modo de dicho Contenido del usuario, ni el uso por parte de UCarga del Contenido del usuario según lo permitido en el presente documento infringirán, malversarán o violarán la propiedad intelectual o los derechos de propiedad de terceros, o los derechos de publicidad o privacidad, o darán lugar a la violación de cualquier ley o reglamento aplicable.</p>
            <p>Usted se compromete a no proporcionar Contenido del usuario que sea difamatorio, calumnioso, odioso, violento, obsceno, pornográfico, ilegal u ofensivo de cualquier otra manera, según lo determine UCarga a su entera discreción, independientemente de que dicho material pueda estar protegido por la ley. UCarga puede, pero no estará obligado a, revisar, supervisar o eliminar el Contenido del usuario, a discreción de UCarga y en cualquier momento y por cualquier motivo, sin previo aviso.</p>
             <h3 className="text-xl font-semibold pt-4">Acceso a la red y dispositivos</h3>
            <p>Usted es responsable de obtener el acceso a la red de datos necesario para utilizar los Servicios. Es posible que se apliquen las tarifas y cuotas de datos y mensajería de su red móvil si accede o utiliza los Servicios desde su dispositivo. Usted es responsable de adquirir y actualizar el hardware o los dispositivos compatibles necesarios para acceder y utilizar los Servicios y las aplicaciones, así como cualquier actualización de los mismos. UCarga no garantiza que los Servicios, o cualquier parte de los mismos, funcionen en un hardware o dispositivos concretos. Además, los Servicios pueden estar sujetos a fallos de funcionamiento y retrasos inherentes al uso de Internet y las comunicaciones electrónicas.</p>
            <h3 className="text-xl font-semibold pt-4">Elección del Derecho aplicable</h3>
            <p>Estas Condiciones se rigen e interpretan de acuerdo con las leyes del Estado de Yucatan., sin dar efecto a ningún conflicto de principios legales, salvo que se disponga lo contrario en las condiciones suplementarias aplicables a su región.</p>
            <h3 className="text-xl font-semibold pt-4">Notificación de infracción de los derechos de autor</h3>
            <p>Es política de UCarga, en las circunstancias apropiadas y a su discreción, desactivar y/o cancelar las cuentas de los usuarios que infrinjan repetidamente o sean acusados repetidamente de infringir los derechos de autor u otros derechos de propiedad intelectual de terceros. De conformidad con la Ley de Derechos de Autor del Milenio Digital de 1998 (la «DMCA») y en reconocimiento de diversas leyes internacionales de derechos de autor, UCarga responderá con prontitud a las notificaciones enviadas al Agente de Derechos de Autor Designado de UCarga (identificado a continuación) con respecto a supuestas infracciones de derechos de autor de terceros en el sitio web de UCarga u otras propiedades digitales de propiedad de UCarga y de acceso público (el/los «Sitio(s)»).</p>
            <p>Un propietario de derechos de autor, persona autorizada para actuar en nombre de uno, o persona autorizada para actuar en virtud de cualquier derecho exclusivo en virtud de derechos de autor puede presentar alegaciones de infracciones de derechos de autor en el Sitio (s) rellenando el siguiente Aviso DMCA de presunta infracción y entregarlo al Agente de Derechos de Autor Designado de UCarga. Tras la recepción de esta Notificación DMCA, UCarga eliminará o bloqueará rápidamente el acceso al contenido presuntamente infractor, notificará al presunto tercero infractor de la misma, y proporcionará al tercero la oportunidad de presentar una contra-notificación para impugnar la presunta infracción. Si se presenta una contranotificación, UCarga la remitirá sin demora al denunciante y restablecerá el contenido eliminado o bloqueado en un plazo de 10 a 14 días laborables, a menos que el denunciante presente pruebas de que ha interpuesto una demanda contra el presunto tercero infractor en relación con el contenido supuestamente infractor.</p>
            <h4 className="text-lg font-semibold pt-2">Notificación DMCA de presunta infracción («Notificación DMCA»)</h4>
            <ul className="list-disc pl-6 space-y-2">
                <li>Identifique la obra protegida por derechos de autor que ha sido infringida o, si esta Notificación DMCA abarca varias obras protegidas por derechos de autor, proporcione una lista representativa de las obras protegidas por derechos de autor que han sido infringidas.</li>
                <li>Identificar el contenido infractor y proporcionar información suficiente para que UCarga pueda localizar el contenido infractor, incluyendo, si procede, la(s) URL(s) del (de los) Sitio(s) donde pueda encontrarse el contenido.</li>
                <li>Proporcione información de contacto, por ejemplo, dirección postal, número de teléfono y dirección de correo electrónico, de la persona que envía esta Notificación DMCA (por ejemplo, el propietario de los derechos de autor o el agente del propietario de los derechos de autor).</li>
                <li>Incluya las dos declaraciones siguientes en el cuerpo de la Notificación DMCA: «Por la presente declaro que creo de buena fe que el uso controvertido del material protegido por derechos de autor no está autorizado por el propietario de los derechos de autor, su agente o la ley (por ejemplo, como uso legítimo).» «Por la presente declaro que la información contenida en esta Notificación DMCA es exacta y, bajo pena de perjurio, que soy el propietario, o estoy autorizado para actuar en nombre del propietario, de los derechos de autor o de un derecho exclusivo en virtud de los derechos de autor que supuestamente se han infringido.»</li>
                <li>Proporcione el nombre legal completo y una firma electrónica o física de la persona que envía esta Notificación DMCA (por ejemplo, el propietario de los derechos de autor o el agente del propietario de los derechos de autor).</li>
            </ul>
            <p>Entregue esta Notificación DMCA, con todos los elementos completados, al Agente de Derechos de Autor Designado de UCarga en Copyright Agent c/o UCarga LLC, 1515 3rd Street, San Francisco, CA 94158.</p>
            <h3 className="text-xl font-semibold pt-4">Aviso</h3>
            <p>UCarga podrá notificar mediante una notificación general en los Servicios, correo electrónico a la dirección de correo electrónico que figure en su Cuenta, o mediante comunicación escrita enviada por correo de primera clase o correo prepagado a la dirección que figure en su Cuenta. Dicha notificación se considerará efectuada una vez transcurridas 48 horas desde su envío por correo postal (si se envía por correo de primera clase o correo prepagado) o 12 horas desde su envío (si se envía por correo electrónico). Usted puede notificar a UCarga, considerándose dicha notificación realizada cuando UCarga la reciba, en cualquier momento por correo de primera clase o correo prepagado a UCarga.</p>
            <h3 className="text-xl font-semibold pt-4">General</h3>
            <p>Usted no puede ceder estas Condiciones sin la aprobación previa por escrito de UCarga. UCarga podrá ceder estas Condiciones sin su consentimiento a: (i) una filial o afiliada; (ii) un adquirente de acciones, negocios o activos de UCarga; o (iii) un sucesor por fusión. Cualquier pretendida cesión que infrinja este apartado será nula. No existe ninguna relación de empresa conjunta, asociación, empleo o agencia entre usted, UCarga o cualquier tercero como resultado de estos Términos o el uso de los Servicios. Si alguna disposición de estas Condiciones se considera inválida o inaplicable, dicha disposición se suprimirá y las disposiciones restantes se aplicarán en la máxima medida permitida por la ley. El hecho de que UCarga no haga valer cualquier derecho o disposición de estas Condiciones no constituirá una renuncia a dicho derecho o disposición, a menos que UCarga lo reconozca y acepte por escrito.</p>
            <h3 className="text-xl font-semibold pt-4">Elección de la lengua</h3>
            <p>Es deseo expreso de las partes que estas condiciones se redacten en inglés. Es voluntad expresa de las partes que estas modalidades y condiciones se redacten y firmen en inglés. Estos términos pueden traducirse a otros idiomas. En caso de diferencia de interpretación entre la versión inglesa de estas condiciones y otra versión, prevalecerá la versión inglesa. Todos los pagos seran realizados mediante pasarela de pago Openpay</p>
          </Section>

        </div>
      </div>
    </div>
  );
}
